/* Publication de contenu MJ. Les parties jouées demeurent locales. */
'use strict';
// Le partage vit dans une fenêtre, ouverte par un bouton de l'en-tête.
const shareDialog=dialog('share-panel','Contenu partagé','<p id="shared-status" class="muted" role="status">Connexion au contenu publié…</p><div class="toolbar"><button id="public-catalog">Consulter les catalogues</button><button id="shared-scene" hidden>Charger la scène publiée</button><button id="shared-login">Connexion MJ</button><button id="shared-publish" hidden>Publier mon contenu</button><button id="shared-logout" hidden>Déconnexion</button></div><label id="shared-auto-label" hidden><input id="shared-auto" type="checkbox" checked> Publier automatiquement mes modifications enregistrées</label><p id="shared-identity" class="muted"></p>');
const shareButton=document.createElement('button');shareButton.id='open-share';shareButton.textContent='Partager';shareButton.onclick=()=>shareDialog.showModal();
document.querySelector('.view-controls').append(shareButton);
let cloud=null,auth=null,admin=false,publishing=false,remote=null,remoteId=null,baseRevision=null,autoReady=false,cloudTimer,unsubscribe,lastPublishedText='',cloudReadGeneration=0;
const status=t=>$('shared-status').textContent=t;
const flagShare=on=>shareButton.classList.toggle('has-news',!!on);
const publicationRef=()=>cloud.doc('amertume_online_public/main');
// Seule la carte ouverte transporte sa mémoire d'exploration : les autres alourdiraient la publication.
function publicMaps(){return structuredClone(maps).map(m=>{if(m.id!==currentMapId){delete m.fog;delete m.seen}return m})}
function publicContent(){saveChecks();savePool();return {schema:1,title:sceneTitle(),round,mode,mapImage,maps:publicMaps(),currentMapId,locked:tokensLocked,catalog:structuredClone(catalog),actors:actors.map(a=>({...structuredClone(a),target:null,checks:[false,false,false]}))}}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(Error('Connexion Firebase indisponible.'));document.head.append(s)})}
function errorText(e){const code=e.code||'';if(code.includes('permission-denied'))return 'Accès Firebase non configuré. Les règles de partage doivent être activées par le MJ.';if(code.includes('unauthorized-domain'))return 'Ajoute valentindrouet-dev.github.io aux domaines autorisés de Firebase Authentication.';if(code.includes('operation-not-allowed'))return 'Active la connexion Google dans Firebase Authentication.';if(code.includes('popup-blocked'))return 'Autorise la fenêtre de connexion Google puis réessaie.';if(code.includes('popup-closed'))return 'Connexion annulée.';return e.message||'Connexion impossible. Les modifications locales sont conservées.'}
async function connectShared(){try{for(const file of ['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js'])await loadScript('https://www.gstatic.com/firebasejs/10.14.0/'+file);const app=firebase.initializeApp(AMERTUME_FIREBASE,'amertume-online');cloud=app.firestore();auth=app.auth();document.dispatchEvent(new Event('amertume-firebase-prete'));auth.onAuthStateChanged(async user=>{admin=false;autoReady=false;document.dispatchEvent(new Event('amertume-mj-change'));$('shared-publish').hidden=true;$('shared-auto-label').hidden=true;$('shared-login').hidden=!!user;$('shared-logout').hidden=!user;$('shared-identity').textContent='';if(user){$('shared-identity').textContent='Compte connecté : '+(user.email||user.uid)+' · Identifiant MJ : '+user.uid;try{const grant=await cloud.doc('amertume_online_admins/'+user.uid).get({source:'server'});if(auth.currentUser?.uid!==user.uid)return;admin=grant.exists&&grant.data().active===true;document.dispatchEvent(new Event('amertume-mj-change'));$('shared-publish').hidden=!admin;$('shared-auto-label').hidden=!admin;if(admin){view='mj';$('view').value='mj';render();status('MJ autorisé. Publie ton contenu local ou charge la version partagée.')}else status('Compte connecté, mais pas encore autorisé comme MJ. Ajoute cet identifiant aux administrateurs Firebase.')}catch(e){status(errorText(e))}}});unsubscribe=publicationRef().onSnapshot(doc=>readPublished(doc),e=>status(errorText(e)))}catch(e){status(errorText(e));$('shared-login').disabled=true}}
async function readPublished(doc){if(!doc.exists){status('Aucun contenu publié. La scène actuelle reste enregistrée sur cet appareil.');baseRevision=null;return}const m=doc.data();if(m.revision===remoteId)return;const gen=++cloudReadGeneration;try{if(!/^[A-Za-z0-9_-]{1,100}$/.test(m.revision)||!Number.isInteger(m.parts)||m.parts<1||m.parts>86)throw Error('Publication invalide.');const chunks=[];for(let i=0;i<m.parts;i++){const p=await cloud.doc('amertume_online_versions/'+m.revision+'/parts/'+i).get();if(!p.exists)throw Error('Publication incomplète : réessaie plus tard.');chunks.push(p.data().data)}const data=SharedData.validate(SharedData.unpack(chunks,m.bytes));if(gen!==cloudReadGeneration)return;remote=data;remoteId=m.revision;if(baseRevision===null)baseRevision=remoteId;$('shared-scene').hidden=false;flagShare(true);if(!admin){status('Catalogue partagé chargé. Tu peux consulter le contenu ou charger la scène publiée.');if(!loading){view='player';$('view').value='player';render()}if(typeof tableId!=='undefined'&&tableId){status('Contenu de la partie reçu.');applyRemote()}}else status(publishing?'Publication en cours…':'Une version partagée est disponible. Tes modifications locales sont conservées.')}catch(e){status(errorText(e))}}
$('shared-login').onclick=async()=>{if(!auth){status('La connexion Firebase n’est pas prête.');return}try{await auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(e){status(errorText(e))}};
$('shared-logout').onclick=async()=>{if(auth)await auth.signOut();admin=false;autoReady=false;status('Déconnecté. Le contenu publié reste consultable.')};
function applyRemote(){if(!remote)return;actors.splice(0,actors.length,...structuredClone(remote.actors).map(normalizeActor));catalog=structuredClone(remote.catalog);maps=Array.isArray(remote.maps)?structuredClone(remote.maps):[];currentMapId=remote.currentMapId||null;tokensLocked=remote.locked===true;round=remote.round||1;mode=remote.mode==='exploration'?'exploration':'combat';owner=actors.findIndex(a=>a.hero);selected=owner;mapImage=remote.mapImage||null;sceneTitle(remote.title||'Amertume');$('round').textContent=String(round).padStart(2,'0');$('map-view').style.backgroundImage=mapImage?'url("'+mapImage+'")':'';$('map').classList.toggle('custom',!!mapImage);baseRevision=remoteId;view=admin?'mj':'player';$('view').value=view;render();scheduleSave();status('Scène partagée chargée.');if(admin){lastPublishedText=JSON.stringify(publicContent());autoReady=true}
 if(typeof reappliquerTable==='function')reappliquerTable()}
$('shared-scene').onclick=()=>{if(confirm('Charger la scène publiée à la place de la scène locale actuelle ?'))applyRemote()};
async function publishShared(explicit=false){if(!admin||!auth?.currentUser){status('Connecte-toi avec un compte MJ autorisé pour publier.');return}if(publishing)return;const value=publicContent(),text=JSON.stringify(value);if(!explicit&&text===lastPublishedText)return;publishing=true;$('shared-publish').disabled=true;let newRef;try{SharedData.validate(value);const packed=SharedData.pack(value);const revision=crypto.randomUUID();newRef=cloud.collection('amertume_online_versions').doc(revision);status('Publication du contenu et des images…');for(let offset=0;offset<packed.chunks.length;offset+=10){const batch=cloud.batch();packed.chunks.slice(offset,offset+10).forEach((data,j)=>batch.set(newRef.collection('parts').doc(String(offset+j)),{data}));await batch.commit()}
 await cloud.runTransaction(async tx=>{const old=await tx.get(publicationRef());const current=old.exists?old.data().revision:null;if(current!==baseRevision)throw Error('Le contenu partagé a changé depuis son chargement. Charge la version partagée avant de republier. Tes modifications locales sont conservées.');tx.set(publicationRef(),{revision,parts:packed.chunks.length,bytes:packed.bytes,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),author:auth.currentUser.uid})});baseRevision=revision;lastPublishedText=text;autoReady=true;status('Contenu publié : le lien de l’app donne accès à cette version sur tous les appareils.');
 }catch(e){autoReady=false;status(errorText(e)+' La publication automatique est suspendue ; utilise Publier pour réessayer.')}finally{publishing=false;$('shared-publish').disabled=false}}
$('shared-publish').onclick=()=>{if(confirm('Publier tous les personnages, monstres, objets, notes et images de cette scène ? Toute personne disposant du lien pourra les consulter.'))publishShared(true)};
function schedulePublish(){if(!admin||!autoReady||!$('shared-auto').checked)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>{if(publishing){schedulePublish();return}publishShared(false)},1800)}
document.addEventListener('submit',e=>{if(['actor-form','item-form','scene-form'].includes(e.target.id))setTimeout(schedulePublish,0)});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&(b.closest('#hp-buttons')||['save-template','delete-actor','delete-item','reset-map'].includes(b.id)||b.hasAttribute('data-cat-add')||b.hasAttribute('data-cat-delete')))setTimeout(schedulePublish,0)});
document.addEventListener('amertume-content-changed',schedulePublish);
const publicDialog=dialog('shared-catalog','Contenu publié','<p class="muted">Lecture seule. Les modifications locales de ta partie ne changent pas le contenu du MJ.</p><div id="shared-catalog-body"></div>');
$('public-catalog').onclick=()=>{const data=remote;if(!data){status('Aucun catalogue partagé accessible pour le moment. Le MJ doit publier son contenu.');return}const row=(title,body)=>'<details class="catalog-row" style="display:block"><summary>'+esc(title)+'</summary><p style="white-space:pre-wrap">'+esc(body)+'</p></details>';$('shared-catalog-body').innerHTML='<h2>Personnages et combattants</h2>'+data.actors.map(a=>row(a.name,a.role+'\nPV '+a.max+' · DEF '+a.def+' · Dégâts '+a.dmg+'\n'+a.notes)).join('')+'<h2>Bestiaire</h2>'+data.catalog.monsters.map(a=>row(a.name,'PV '+a.pv+' · DEF '+a.def+' · Dégâts '+a.damage+' · XP '+a.xp+'\n'+(a.notes||''))).join('')+'<h2>Armurerie</h2>'+data.catalog.items.map(a=>row(a.name,(a.category==='armor'?'DEF '+a.def:keys.map((k,i)=>a.dice?.[k]?a.dice[k]+' '+types[i]:'').filter(Boolean).join(' · '))+'\n'+(a.effects||'')+'\n'+(a.notes||''))).join('');publicDialog.showModal()};
connectShared();
